spring.application.name=service-registry
server.port=8761

# Eureka Server configuration

# Since this is a Eureka Server, it should not register itself as a client.
eureka.client.register-with-eureka=false

# Since this is a Eureka Server, it should not fetch registry information from itself.
# Do not fetch registry from another Eureka server, as this is a standalone server.
eureka.client.fetch-registry=false

#Eureka server runs on localhost, so we set the hostname to localhost and prefer IP address for registration.
eureka.instance.hostname=localhost

# Services will register using IP instead of hostname, which is useful in containerized environments where hostname may not be resolvable.
eureka.instance.prefer-ip-address=true

# Set the lease renewal interval and expiration duration to ensure that the Eureka server can detect when a service instance goes down. This is especially important in development environments where services may be restarted frequently.
eureka.instance.lease-renewal-interval-in-seconds=10

# If no heartbeat for 30 seconds, service is removed from registry. This is a short duration for development purposes, allowing the Eureka server to quickly detect when a service instance goes down and remove it from the registry.
eureka.instance.lease-expiration-duration-in-seconds=30
